name: Scribe GitHub App Workflow Demo
on: [push]
jobs:
  #Explore-GitHub-Actions:
  #  runs-on: ubuntu-latest
  #  steps:
  #    - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
  #    - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
  #    - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
  #    - name: Check out repository code
  #      uses: actions/checkout@v3
  #    - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
  #    - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
  #    - name: List files in the repository
  #      run: |
  #        ls ${{ github.workspace }}
  #    - run: echo "ğŸ This job's status is ${{ job.status }}."
  scribe-report-test:
    runs-on: ubuntu-latest
    steps:
      - name: Generate cyclonedx json SBOM - add metadata - labels, envs, name
        id: gensbom_labels
        uses: scribe-security/actions/gensbom/bom@master
        with:
          target: 'busybox:latest'
          verbose: 3
          format: json
          force: true
          name: name_value
          env: test_env
          label: test_label
        env:
          test_env: test_env_value

      - name: Generate cyclonedx json SBOM
        id: gensbom_json
        uses: scribe-security/actions/gensbom/bom@master
        with:
          target: 'busybox:latest'
          format: json
          force: true
          output.path: ./provenance.json

      - uses: actions/upload-artifact@v2
        with:
          name: provenance
          path: ${{ steps.gensbom_json.outputs.OUTPUT_PATH }}

      - name: Generate slsa prov statement
        id: slsa_statement
        uses: scribe-security/actions/gensbom/bom@master
        with:
          target: 'busybox:latest'
          format: statement-slsa

      - uses: actions/upload-artifact@v2
        with:
        name: scribe-evidence
        path: ${{ steps.slsa_statement.outputs.OUTPUT_PATH }}

